[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
encase = "0.6.1"
pollster = "0.3.0"
wgpu = "0.16.2"
winit = "0.28.6"
